#!/bin/sh
set -e

case "$AWAIT_AKENEO_BUILD_DONE" in
    0|""|false|"false" ) ;;
    * )
        echo "Waiting for app installation to be ready"
        while [ ! -f ./vendor/akeneo-build-done ]
        do
            sleep 1
        done
    ;;
esac

if [ -f ./bin/akeneo-bootstrap ]
then
    ./bin/akeneo-bootstrap
else
    echo "[WARNING] Could not find akeneo-bootstrap script" 1>&2
fi

$@