version: '3'
services:
  akeneo_web:
    build: "."
    links:
      - "mariadb:db"
      - "mongo:mongodb"
    volumes:
      - "akeneo:/var/www/html"
      - "packages:/src/packages"
    ports:
      - "8080:80"
    environment:
      DATABASE_HOST: "db"
      DATABASE_NAME: "akeneo"
      DATABASE_USER: "akeneo"
      DATABASE_PASSWORD: "akeneo"
      MONGODB_SERVER: "mongodb://mongodb:27017"
      MONGODB_DATABASE: "akeneo"
      PIM_CATALOG_PRODUCT_STORAGE_DRIVER: "doctrine/mongodb-odm"
  akeneo_app:
    image: netresearch/akeneo-app
    volumes:
      - "akeneo:/var/www/html"
      - "packages:/src/packages"
  mariadb:
    image: "mariadb:5.5"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "akeneo"
      MYSQL_USER: "akeneo"
      MYSQL_PASSWORD: "akeneo"
  mongo:
    image: "mongo:2.6"

volumes:
  akeneo:
  packages:
