#!/bin/bash
set -e

if [ $AWAIT_AKENEO_INSTALLATION_DONE > 0 ]
then
    echo "Waiting for app installation to be ready"
    while [ ! -f ./vendor/installation-done ]
    do
        sleep 1
    done
fi

if [ -f ./bin/akeneo-bootstrap ]
then
    ./bin/akeneo-bootstrap
else
    echo "[WARNING] Could not find akeneo-bootstrap script" 1>&2
fi

$@